### PR TITLE
updated architure diagram

### PR DESCRIPTION
**Pull request by markllama**
This document/graphic updates the architecture design.  It removes unneeded Floating IP addresss and more correctly reflects the layout of the OpenShift "Router" and the location of the infrastructure (aka "Bastion") host.

### CODE REVIEW

**Comment by juddmaltin-dell** [comment]
Good changes.  Could you indicate which of the "Routers" is a router created by OpenStack, or the OpenShift "Reverse Proxy/Router"

Btw, what tool do you use for the images.

**Comment by jprovaznik** [comment]
"Every VM gets a floating IP" might be removed.

Side note: we don't assign floating IP to openshift router ATM (IOW it's not accessible from outside), which we probably should - I've added this to trello board, not something which should be addressed in this diagram.

**Comment by markllama** [comment]
@juddmaltin-dell I'm creating the image in Google draw with image templates from an internal icon set from our marketing people.  THen I'm exporting as both SVN and PNG.  The PNG can't be easily edited.  The SVN could become the "canonical" version if somone wanted to use an SVN editor like Inkscape in the future.

**Comment by markllama** [comment]
@jprovaznik  updated.

**Pull request merged**
