### PR TITLE
Switch to ansible 2.1

### PR DESCRIPTION
**Pull request by jprovaznik**
Ansible 2.1 is now required by openshift-ansible

Fixes: #181
Fixes: #185

### CODE REVIEW

**Comment by jprovaznik** [comment]
Still WIP - not tested yet.

**Comment by jprovaznik** [comment]
Hm, this needs more love - doesn't work.

**Comment by jprovaznik** [comment]
It should work now, @cbrown2 let me know if this works for you (git_rev should point back to master in the env_file)

**Comment by snecklifter** [comment]
@jprovaznik thanks, testing now, will update shortly

**Comment by snecklifter** [comment]
@jprovaznik thanks, I can confirm that has built successfully using flannel, no load balancer and no private registry.

**Comment by jprovaznik** [comment]
Note that with ansible 2.1 there is now a performance regression issue. Installation passes, but takes significantly longer than used to be (2x times on 1 master, 2 nodes).
https://bugzilla.redhat.com/show_bug.cgi?id=1360440

**Comment by snecklifter** [comment]
@jprovaznik ok, thanks for the heads up. Please ping us for additional testing as we have no deployed to production yet.

**Pull request merged**
