### PR TITLE
LBaaS + external DNS

### PR DESCRIPTION
**Pull request by jprovaznik**

### CODE REVIEW

**Comment by markllama** [comment]
Attempting stack-create I get a quick fail:

```
| stack_status_reason   | Resource CREATE failed: NeutronClientException:                                                                                                                                                        |
|                       | resources.lb_monitor: 404 Not Found  The resource could                                                                                                                                                |
|                       | not be found.    
```

**Comment by markllama** [comment]
Using Neutron 2015.1.2

```
openstack-heat-engine-2015.1.2-9.el7ost.noarch
openstack-heat-common-2015.1.2-9.el7ost.noarch
openstack-heat-api-cloudwatch-2015.1.2-9.el7ost.noarch
python-heatclient-0.6.0-1.el7ost.noarch
openstack-heat-api-cfn-2015.1.2-9.el7ost.noarch
openstack-heat-api-2015.1.2-9.el7ost.noarch

python-neutron-2015.1.2-9.el7ost.noarch
python-neutronclient-2.4.0-2.el7ost.noarch
openstack-neutron-common-2015.1.2-9.el7ost.noarch
openstack-neutron-ml2-2015.1.2-9.el7ost.noarch
openstack-neutron-2015.1.2-9.el7ost.noarch
openstack-neutron-openvswitch-2015.1.2-9.el7ost.noarch
```

**Comment by jprovaznik** [comment]
@markllama: you probably don't have lbaas installed. When using packstack it's "--os-neutron-lbaas-install=y" option. I'll add a note about this requirement into README.

**Comment by markllama** [comment]
Harumph.  I found that my configuration does not have LBaaS enabled.  Fixing.

**Comment by lebauce** [comment]
LGTM.
Could you please rebase ?

**Comment by jprovaznik** [comment]
rebased

**Pull request merged**
