### PR TITLE
fall back to epel-release-latest-7 if hardcoded 7-minor unavailable

### PR DESCRIPTION
**Pull request by juddmaltin-dell**

### CODE REVIEW

**Comment by juddmaltin-dell** [comment]
@markllama @lebauce @javierpena

**Comment by lebauce** [comment]
Thank you for this. Trying it right now.
Regarding customize-disk-image, I think we can use `epel-release-latest-7`. Do you mind updating it with the commit message ?

Thanks !

**Comment by juddmaltin-dell** [comment]
Done as requested.  Happy to help!

**Comment by lebauce** [comment]
@juddmaltin-dell I squashed your commits into one and merged it. Thanks !

**Pull request closed without merging**
