### PR TITLE
Dry common functions

### PR DESCRIPTION
**Pull request by jprovaznik**

### CODE REVIEW

**Comment by jprovaznik** [comment]
Don't merge yet, tests are still running

**Comment by jprovaznik** [comment]
Except some other issues this PR causes that we don't fit into 65K cloud-init data limit for infra node:
| oshift31                  | dc830001-3643-4033-ad75-0b5263c72fee | Resource CREATE failed: BadRequest: resources.infra_host.resources.host: User data too large. User data must be no larger than 65535 bytes once base64 encoded. Your data is 65928 bytes (HTTP 400) (Request-ID: req-eaa7c3fb-3541-4ec6-9fac-5da7088ab8c4) | CREATE_FAILED      | 2016-04-12T09:46:04 |

**Comment by markllama** [comment]
If you REALLY want to get DRY, I think _master-boot.sh_ and _node-boot.sh_ are identical.  Replace with _ose-host-boot.sh_ ?

**Comment by jprovaznik** [comment]
Yes, this patch address master|node-boot scripts among others. The problem was 65K limit, an option would be to have common lib for all nodes, and then common lib for ose nodes so these ose-related functions are don't increase overall size on infra node (which is the one hitting the limit)

**Comment by jprovaznik** [comment]
this patch needs bigger rebase since a lot has change meantime, don't merge yet.

**Comment by jprovaznik** [comment]
refactored to reflect changes in code

**Comment by jprovaznik** [comment]
rebased

**Pull request merged**
