### PR TITLE
Converted README.rst to Asciidoc

### PR DESCRIPTION
**Pull request by markllama**
Converted README to Asciidoc. 
Added language sensitive formatting to shell and yaml code blocks
Added explanatory comments to openshift parameter files
Gave parameter files a descriptive name.

### CODE REVIEW

**Comment by markllama** [comment]
Update with LB references from new README.rst

**Comment by jprovaznik** [comment]
What about the old README.rst file? It seems it should be deleted to avoid confusion. The patch should be OK, though it's very difficult to check it if file renaming is done together with other changes. Could you please split changes and renaming into separate patches next time? (not this time as I understand it would be quite painful to try to split it now).

**Comment by markllama** [comment]
Renaming adoc to rst requires some changes, but they should only be formatting.  If I made textual changes too I apologize.

**Comment by markllama** [comment]
I actually left the .rst for this for comparison purposes.  I'll remove it now and we can merge?
- Mark

**Comment by markllama** [comment]
removed README.rst
removed trailing whitespace in adoc

**Pull request merged**
