### PR TITLE
Refactor fragments - simplest scripts

### PR DESCRIPTION
**Pull request by markllama**
This PR adds comments and some structure to the scripts and file fragments used to configure the hosts which will run OpenShift prior to the execution of Ansible to perform the installation and configuration.

This PR addresses only the simplest of these scripts.  One or more later PRs will address the more complex scripts which are run at VM boot.

The changes included here must have _no effect_ on behavior of the scripts and files.  The changes are solely to provide structure to make it easier to use and maintain the Heat stack in the future.

### CODE REVIEW

**Comment by jprovaznik** [comment]
Hi Mark, thanks for sending the patch - I added couple of comments to one of patches. My personal opinion is that maybe we might slow down with comments density and put comments only to parts/block which might be unclear.

**Comment by markllama** [comment]
So far all of the notes are "there are too many comments".  Are there any _technical_ notes?

**Comment by jprovaznik** [comment]
The first comment about ENV_VARS is not related to comments density. I think yesterday we didn't come to consensus about what needs to be commented and what not . As I said before, I think this is too much - comments similar to what I commented in one of patches might be IMO removed, but I'm open to others opinion. On the other side it's not a big deal, so if you guys are happy with current version I can live with it :).

**Comment by lebauce** [comment]
@markllama LGTM even it makes a bit too much comment for me :-) Could you please squash the commits into one single commit please ?

**Pull request merged**
