### PR TITLE
katello consumer ca cert install fails when using https or yum install

### PR DESCRIPTION
**Pull request by wrichter**
changed the rhn registration script to use http instead of https and yum localinstall instead of yum install to ensure that katello consumer ca installation does not fail

### CODE REVIEW

**Review by markllama — CHANGES_REQUESTED** [review]
I'd prefer to leave this as https and add --nogpgcheck to the yum localinstall command.

**Review by markllama — APPROVED** [review]
I've tried localinstall with --nogpgcheck and only the http method works.

Approved.

**Comment by tomassedovic** [comment]
Thanks!

**Comment by wrichter** [comment]
I think the reason we have to fall back to http is that satellite / katello create their own self-signed CA cert which is used to sign the certs used for the TLS handshake (which are probably not present on the KVM image).  --nogpgcheck applies to the actual content that would be transmitted via https, but the connection fails before any content is transmitted.

Note that I haven't been successful to replace the katello CA cert with a properly signed one so far - there is a method described in the satellite docs but the one time i tried it left my installation in an unusable state.

**Pull request merged**
