### PR TITLE
Reports stack completion only once the cluster is fully setup

### PR DESCRIPTION
**Pull request by drebes**
A basic wait condition on the master setup to fix the stack creation reporting completion too early.

### CODE REVIEW

**Comment by tomassedovic** [comment]
Thanks and sorry for waiting so long (I was sick). This is awesome but I'd like to wait merging this after #2 as it should be easier to resolve potential merge conflicts here.

Looks good to merge so I'll do that (fixing any conflicts) once the other pull request is in.

**Comment by drebes** [comment]
No worries, I'm very interested in #2 as well. I can update this PR once that is merged.

**Comment by tomassedovic** [comment]
@drebes okay, the previous PR was merged. Can you rebase this please?

**Comment by drebes** [comment]
I did the rebase, but please don't merge it just yet, I still need to do some more testing.

**Comment by drebes** [comment]
This now should be good to go.

**Comment by tomassedovic** [comment]
Thanks!

**Pull request merged**
