### PR TITLE
DNS dynamic update improvement

### PR DESCRIPTION
**Pull request by jfcoz**
allow to specify the dns master server to use (default to first of dns_servers)
allow to specify the dns update key name (default to update-key)

there are many uses cases : 
- For example the DNS that you use to resolve are not the authoritative DNS for the zone that you want to update.
- Or also if the first DNS in resolv.conf is the nearest one (for shorter latency), and not the master.

For the keyname, "update-key" is the hardcoded value in fragments/update_dns.py and in osp-dns ( https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/osp-dns/ansible/templates/update.key.j2 ) but for production servers there is not only one key.

### CODE REVIEW

**Comment by ioggstream** [comment]
@jfcoz you are using:

- a dns server for server
- a different master dns server for updates?

I'd explicit better the use case in the PR.

**Comment by jfcoz** [comment]
@ioggstream , there are many uses cases : 
- For example the DNS that you use to resolve are not the authoritative DNS for the zone that you want to update.
- Or also if the first DNS in resolv.conf is the nearest one (for shorter latency), and not the master.

For the keyname, "update-key" is the hardcoded value in fragments/update_dns.py and in osp-dns ( https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/osp-dns/ansible/templates/update.key.j2 ) but for production servers there is not only one key.

**Comment by ioggstream** [comment]
@jfcoz Nice, edit the PR description then ;)

I usually use dedicated DNS for OCP. Then I delegate the OCP zone to that. this enables "hiding" OCP infra address from outside the mgmt area.

**Comment by jfcoz** [comment]
Dead project

**Pull request closed without merging**
