### PR TITLE
Timezone support #344.

### PR DESCRIPTION
**Pull request by ioggstream**
Added `timezone` parameter to `openshift.yaml`.

The  default is `Etc/UTC`.

Feedback welcome!

### CODE REVIEW

**Comment by markllama** [comment]
Heh.  Personally, as someone who's run services at global ISPs, There Is Only One Timezone and It Is UTC.

That said, I'm not the only person with an opinion.  We'll have to get some feedback from others.  I'll take a look.

**Comment by ioggstream** [comment]
Hi @markllama. Agreed. 

It may happen that some iso images are PDT or other (maily us) timezones. Adding this param:

  - we ensure the tz is UTC by default
  - we enable customizations (I'm deliverying a self-service, per-tenant openshift) 

Thx for your feedback + Peace,
R.

**Comment by tomassedovic** [comment]
What worries me here that this change seems to have nothing to do with openshift as such and I worry that we'd end up with options for every conceivable server configuration.

I have 2 questions @ioggstream:

1. does this have to be set before the openshift installation or can it happen afterwards
2. would you be okay with a more general approach: e.g. specifying extra cloud-config options or maybe a custom pre-installation playbook you could pass in the Heat parameters?

**Comment by ioggstream** [comment]
@tomassedovic Thanks for answering!

  1. a more general approach is fine: I agree about avoiding server-parameter proliferation
  2. using heat in some way (eg. all hosts inherit a CloudConfig from openshift.yaml) can be fine
  3. using ansible: this means we get logs with bad timestamps during cloud-init. This makes debugging hard when cross-checking bw openstack and openshift-on-openstack

Feel free to spam me at will here and on #openshift ;) 

Thx++,
R.

**Comment by ioggstream** [comment]
@tomassedovic @markllama  I implemented your suggested approach in #356 . 

We could move much of the boilerplate code there too ;)

Let me know + Peace,
R.

**Pull request closed without merging**
